//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смежность вершин.
        /// </summary>
        internal static string AdjacementMessageBoxLabel {
            get {
                return ResourceManager.GetString("AdjacementMessageBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string AdjacementNoAnswer {
            get {
                return ResourceManager.GetString("AdjacementNoAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string AdjacementYesAnswer {
            get {
                return ResourceManager.GetString("AdjacementYesAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создайте или загрузите граф.
        /// </summary>
        internal static string AssertGraphWarningMessageBox {
            get {
                return ResourceManager.GetString("AssertGraphWarningMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найдены вершины для отрисовки.
        /// </summary>
        internal static string DrawEdgeWarningMessageBox {
            get {
                return ResourceManager.GetString("DrawEdgeWarningMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вес ребра.
        /// </summary>
        internal static string EdgeWeightMessageBoxLabel {
            get {
                return ResourceManager.GetString("EdgeWeightMessageBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите вес вершины.
        /// </summary>
        internal static string EnterEdgeWeight {
            get {
                return ResourceManager.GetString("EnterEdgeWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите номер первой вершины.
        /// </summary>
        internal static string EnterFirstVertexNumber {
            get {
                return ResourceManager.GetString("EnterFirstVertexNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите номер второй вершины.
        /// </summary>
        internal static string EnterSecondVertexNumber {
            get {
                return ResourceManager.GetString("EnterSecondVertexNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string ErrorMessageBoxLabel {
            get {
                return ResourceManager.GetString("ErrorMessageBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный вес вершины.
        /// </summary>
        internal static string IncorrectEdgeWeight {
            get {
                return ResourceManager.GetString("IncorrectEdgeWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный первый номер вершины.
        /// </summary>
        internal static string IncorrectFirstVertexNumber {
            get {
                return ResourceManager.GetString("IncorrectFirstVertexNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный второй номер вершины.
        /// </summary>
        internal static string IncorrectSecondVertexNumber {
            get {
                return ResourceManager.GetString("IncorrectSecondVertexNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        internal static string InfoMessageBoxLabel {
            get {
                return ResourceManager.GetString("InfoMessageBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите номер вершины.
        /// </summary>
        internal static string TryGetInt32InfoMessageBox {
            get {
                return ResourceManager.GetString("TryGetInt32InfoMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный номер вершины.
        /// </summary>
        internal static string TryGetInt32WarningMessageBox {
            get {
                return ResourceManager.GetString("TryGetInt32WarningMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество ребер:.
        /// </summary>
        internal static string UpdateEdgeLabel {
            get {
                return ResourceManager.GetString("UpdateEdgeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество вершин:.
        /// </summary>
        internal static string UpdateVertexLabel {
            get {
                return ResourceManager.GetString("UpdateVertexLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение.
        /// </summary>
        internal static string WarningMessageBoxLabel {
            get {
                return ResourceManager.GetString("WarningMessageBoxLabel", resourceCulture);
            }
        }
    }
}
